### ISSUE TITLE
[BUG] thumbnails are empty

### ISSUE THREAD

**Issue by Subtixx** [AlexPresso/VideoStation-FFMPEG-Patcher#40] opened 2022-05-23 21:35 UTC
**System details**
- Synology model: DS3617xs
- DSM version: 6.2
- SynoCommunity FFMPEG Version: 4.4.2-43
- VideoStation version: 2.4.10-1632
- Advanced Media Extensions version: none

**Describe the bug**
I'm really embarrassed to open a new bug report right away. But after switching to your ffmpeg and adding the files for ther workaround of #39 I do not receive any thumbnails anymore. It says: Error while opening decoder for input stream #0:0 : Operation not permitted

**Provide Log files**

## `ffmpeg.log` (containing the ffmpeg-wrapper execution logs)
https://gist.github.com/Subtixx/bd1eebf65d303992d4ea1a066236fbe8

**Comment by AlexPresso** [comment] 2022-05-24 11:55
Do you mean you executed the patcher from the pull request I linked ? Actually don't do it for now, it's a Work In Progress and not working at all for now.

**Comment by Subtixx** [comment] 2022-05-24 12:19
No no. I used the master of this repository.

Before I patched my ffmpeg using the script in the repository thumbnails were generated. Now after executing the patch using `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash` it does not generate thumbnails for videos anymore.

**Comment by AlexPresso** [comment] 2022-06-04 11:05
Hi Subtixx,
The new wrapper may fix this issue, if you want to give it a try you can use the following commands:
- `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch`
- `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -b new_wrapper`

**Comment by Subtixx** [comment] 2022-06-04 19:58
First I had to use the following:

`curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | sudo bash -s -- -a unpatch`
`curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | sudo bash -s -- -b new_wrapper`

else I would get "permission denied" on alot of the commands.

And now I get just those errors:

```
[2022-06-04 21:51:29] [INFO] ========================================[start ffmpeg 24753]
[2022-06-04 21:51:29] [INFO] DEFAULT_ARGS: -timelimit 20 -an -ss 5 -i /volume1/Videos/blubb.mp4 -vframes 1 -vf scale=size=hd480:force_original_aspect_ratio=decrease -f mjpeg -y /volume1/Videos/@eaDir/blubb.mp4/SYNOVIDEO_TEMP.jpg
[2022-06-04 21:51:29] [ERROR] Error on line 48 /var/packages/VideoStation/target/bin/ffmpeg
[2022-06-04 21:51:29] [INFO] ========================================[end ffmpeg 24753]


[2022-06-04 21:51:29] [INFO] ========================================[start ffmpeg 24764]
[2022-06-04 21:51:29] [INFO] DEFAULT_ARGS: -timelimit 60 -an -i /volume1/Videos/blubb.mp4 -ss 5 -vframes 1 -vf scale=size=hd480:force_original_aspect_ratio=decrease -f mjpeg -y /volume1/Videos/@eaDir/blubb.mp4/SYNOVIDEO_TEMP.jpg
[2022-06-04 21:51:29] [ERROR] Error on line 48 /var/packages/VideoStation/target/bin/ffmpeg
[2022-06-04 21:51:29] [INFO] ========================================[end ffmpeg 24764]


[2022-06-04 21:51:29] [INFO] ========================================[start ffmpeg 24774]
[2022-06-04 21:51:29] [INFO] DEFAULT_ARGS: -timelimit 240 -an -i /volume1/Videos/blubb.mp4 -ss 3 -vframes 1 -vf scale=size=hd480:force_original_aspect_ratio=decrease -f mjpeg -y /volume1/Videos/@eaDir/blubb.mp4/SYNOVIDEO_TEMP.jpg
[2022-06-04 21:51:29] [ERROR] Error on line 48 /var/packages/VideoStation/target/bin/ffmpeg
[2022-06-04 21:51:29] [INFO] ========================================[end ffmpeg 24774]
```

**Comment by AlexPresso** [comment] 2022-06-04 20:54
Have you runned the script using root user ?

**Comment by AlexPresso** [comment] 2022-06-04 21:14
The new wrapper directly pass the VideoStation args to the SynoCommunity ffmpeg. The patch isn't editing anything related to the `eaDir`, I also cannot reproduce the issue, my VideoStation (without patch) never generates an eaDir

**Comment by Subtixx** [comment] 2022-06-05 07:24
The @ eaDir is only visible using WinSCP / SCP, it does not show up in SMB nor in filestation. The directory contains all thumbnails / covers that VideoStation uses and generates from the video by default (the little images you see in the list of the videos)

Output of the patcher:
```
[2022-06-05 09:22:37] [INFO] ffmpeg-patcher v1.5
[2022-06-05 09:22:37] [Message of the day]

The patcher was redesigned to include an unpatch procedure.

I'm aware of an issue with HEVC and I'm working on it.

As always, please let me know of any issue you could have.

[2022-06-05 09:22:38] [INFO] You're running DSM 6.2
[2022-06-05 09:22:38] [INFO] ====== Patching procedure (branch: new_wrapper) ======
[2022-06-05 09:22:38] [INFO] Saving current ffmpeg as ffmpeg.orig
[2022-06-05 09:22:38] [INFO] Downloading ffmpeg's wrapper...
[2022-06-05 09:22:38] [INFO] Saving current libsynovte.so as libsynovte.so.orig
[2022-06-05 09:22:38] [INFO] Enabling eac3, dts and truehd
[2022-06-05 09:22:38] [INFO] Restarting VideoStation...
package VideoStation restart successfully

[2022-06-05 09:22:42] [INFO] Done patching, you can now enjoy your movies ;) (please add a star to the repo if it worked for you)
```

**Comment by AlexPresso** [comment] 2022-06-05 09:45
All the args are already printed, it's the `DEFAULT_ARGS` (args are never modified) logs entry.
Using `$@` is a reference to the args array itself, when trying to print it, it will bug and only print the first array index. If you want to convert the whole array to a string, you need to use `$*`

**Comment by AlexPresso** [comment] 2022-06-05 09:50
I just noticed you're running on an old VideoStation version, they may have changed the behavior of `@eaDir` because mine is always empty, even if the video thumbnails are working (both Movies and Series episodes).

Still, it's a strange behavior, because I remember having them working fine before I upgraded to the latest version of DSM + VideoStation

**Comment by Subtixx** [comment] 2022-06-05 11:31
I cannot explain why the VideoStation should be an old version, I pretty much use the latest available in Package Manager:
![grafik](https://user-images.githubusercontent.com/20743379/172048329-5eb53282-a450-4b6a-ae17-7c4013adbfc4.png)

Either way permissions on my `@eaDir` is 0777:
![grafik](https://user-images.githubusercontent.com/20743379/172048354-dd1207ac-b77b-4b2c-9146-4b7153267cf9.png)

Permissions on `/var/packages/ffmpeg/target/bin/ffmpeg`:
![grafik](https://user-images.githubusercontent.com/20743379/172048401-92b0fd23-d565-43f3-9db0-fd32eee5dc7f.png)

**Comment by AlexPresso** [comment] 2022-06-05 11:37
It's the latest available for your DSM version, but updating to DSM 7.1 allows you to update VideoStation to 3.0.3

**Comment by AlexPresso** [comment] 2022-06-08 11:41
Could you provide me these files please, so I can compare them before and after the patch:
- `/var/packages/VideoStation/target/lib/libsynovte.so`
- `/var/packages/VideoStation/target/lib/libsynovte.so.orig`

If you want, you can copy them to the `/volume1/homes/<your user>` and download them using FileStation

**Comment by Subtixx** [comment] 2022-06-08 19:22
Sure ca
[libsynovte.zip](https://github.com/AlexPresso/VideoStation-FFMPEG-Patcher/files/8864464/libsynovte.zip)
n

**Comment by AlexPresso** [comment] 2022-10-31 20:38
Hey there,

Sorry for the delay. It may be an issue with the old VideoStation because I cannot reproduce the issue and the only differences between the two files are for the patched codec names:

`diff  -u  <(xxd libsynovte.so) <(xxd libsynovte.so.orig) | nano -`

```diff
--- /dev/fd/63  2022-10-31 21:35:50.931184807 +0100
+++ /dev/fd/62  2022-10-31 21:35:50.927184805 +0100
@@ -19799,7 +19799,7 @@
 0004d560: 3d00 266d 6574 686f 643d 0026 5f73 6964  =.&method=.&_sid
 0004d570: 3d00 2653 796e 6f54 6f6b 656e 3d00 6175  =.&SynoToken=.au
 0004d580: 6469 6f5f 666f 726d 6174 0061 6333 5f63  dio_format.ac3_c
-0004d590: 6f70 7900 3363 6165 0079 7576 3432 3070  opy.3cae.yuv420p
+0004d590: 6f70 7900 6561 6333 0079 7576 3432 3070  opy.eac3.yuv420p
 0004d5a0: 002d 7069 785f 666d 7400 2d73 6567 6d65  .-pix_fmt.-segme
 0004d5b0: 6e74 5f66 6f72 6d61 7400 6d70 6567 7473  nt_format.mpegts
 0004d5c0: 002d 7365 676d 656e 745f 6c69 7374 5f74  .-segment_list_t
@@ -20364,7 +20364,7 @@
 0004f8b0: 4b53 7436 7665 6374 6f72 4953 7353 6149  KSt6vectorISsSaI
 0004f8c0: 5373 4545 524b 5373 4555 6c76 455f 006c  SsEERKSsEUlvE_.l
 0004f8d0: 6962 6661 6163 006c 6962 6d70 336c 616d  ibfaac.libmp3lam
-0004f8e0: 6500 7374 6400 6468 6575 7274 006d 7065  e.std.dheurt.mpe
+0004f8e0: 6500 6474 7300 7472 7565 6864 006d 7065  e.dts.truehd.mpe
 0004f8f0: 6734 0068 3236 3400 6d70 6567 3276 6964  g4.h264.mpeg2vid
 0004f900: 656f 0076 6331 0077 6d76 3300 7276 3430  eo.vc1.wmv3.rv40
 0004f910: 0068 6576 6300 4449 5658 0048 6967 6820  .hevc.DIVX.High
```

**Comment by AlexPresso** [comment] 2022-12-12 21:40
I'll close this issue, feel free to reopen it if you need to.

**Closed by AlexPresso** 2022-12-12 21:40 UTC
Labels: awaiting feedback
