### ISSUE TITLE
DSM 7.1-42661 Update 1 spin on Chromecast

### ISSUE THREAD

**Issue by JeromeTra** [AlexPresso/VideoStation-FFMPEG-Patcher#29] opened 2022-05-06 17:28 UTC
Hi !
First, great job, it work well, before i update the Syno ;)

Advanced Media Extensions version: 2.0.0-1017
VideoStation version: 3.0.3-2084
SynoCommunity FFMPEG version: 4.4.2-43
Synology model: DS220+
DSM 7.1-42661 Update 1

I Can launch movie (EAC3) on DSVideoStation on Windows (need external player like VLC), Iphone and Ipad with no error, like before update

But, i can't cast to Chromecast (Bbox Miami) whith EAC3 audio, AAC_LC work.

Any idea ? i have already test the last closed issue's solution (dsm 7.1 codec not working #26)

**Comment by AlexPresso** [comment] 2022-05-08 09:36
Hi,

Unfortunately, I don't have a chromecast so it'll be hard for me to test it. But I know there's a setting in the VideoStation options, to enable AC3 passthrough on chromecast, could you give it a try please ?

**Comment by JeromeTra** [comment] 2022-05-08 09:41
Hi, I have already tested AC3 passthrough in Videostation option but that didn't change anything.

**Comment by AlexPresso** [comment] 2022-05-08 09:52
Okay, hopefully we have some informations in the logs, could you please follow the following steps:

- Start the video on VideoStation, wait for the video to play and put the browser in background (keep the video playing)
- Connect through SSH ([help](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/General_Setup/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet))
- Switch to root user: `sudo -i`

## `ffmpeg.log` (containing the ffmpeg-wrapper execution logs)
- Go to the temporary directory: `cd /tmp`
- Type `ls -al | grep ffmpeg` to list all files containing "ffmpeg" and check you have one named `ffmpeg.log`
- Type `tail -200 ffmpeg.log` to print the last 200 lines to the console
- Copy paste those lines in a new [gist](https://gist.github.com/)

## `ffmpeg-FFMxxxx.stderr` (containing chunks transcoding operations)
- When you ran `ls -al | grep ffmpeg` you should have seen another file that looks like `ffmpeg-FFMxxxx.stderr`
- Type `tail -100 ffmpeg-FFMxxxx.stderr` (replacing the filename by the correct one)
- Copy paste those lines in a new [gist](https://gist.github.com/)
- Type `head -300 ffmpeg-FFMxxxx.stderr` (replacing the filename by the correct one)
- Copy paste those lines in another new [gist](https://gist.github.com/)
- Copy paste all the gists links in a new comment :)

**Comment by JeromeTra** [comment] 2022-05-08 16:43
ok,
So, the link to the gist (i hope that it's ok ;) ) : https://gist.github.com/JeromeTra/70a30f96f0763db53c8a5fa6f5bd9861
But sorry, no *.stderr file on the Syno

**Comment by AlexPresso** [comment] 2022-05-08 17:19
Nice ! I need to decompile VideoStation to check something but I think I know why it failed, thanks for the gist.
I'll come back to you ;)

**Comment by AlexPresso** [comment] 2022-05-23 21:17
Hi Jerome,

Your issue will be fixed by the new wrapper. You can check the pull request from time to time to be informed of the advancement.

You'll have to repatch VideoStation, but only after the pull request is merged on the main branch (no worries, you'll receive a notification).

**Comment by JeromeTra** [comment] 2022-05-24 07:18
Hi Alex !

Thanks for your great job !
If you need other logs or test,i'm ready to help you ;)

Have a nice day,

**Comment by Fabian1601** [comment] 2022-06-02 04:51
Alex, I think the problem could also be solved with the new wrapper ;)

**Comment by AlexPresso** [comment] 2022-06-02 10:47
Absolutely, just needed you to test it before I ask someone else to do so

@JeromeTra Could you please run the following commands and tell me if the issue is fixed with the new wrapper:
- `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -a unpatch`
- `curl https://raw.githubusercontent.com/AlexPresso/VideoStation-FFMPEG-Patcher/main/patcher.sh | bash -s -- -b new_wrapper`

**Comment by JeromeTra** [comment] 2022-06-02 11:48
Hi Alex !
Great job ! it works like a charm when casting to BBox Miami (Chromecast) ! 
Tested with this Videostation parameters : 
Transcodage Video : ON
Audio Remuxing : OFF
Passthrough AC3 : ON  
Chromecast Passthrough AC3 : ON

**Comment by AlexPresso** [comment] 2022-06-02 13:22
Nice :)
Don't close the issue, it will be done automatically by the pull-request

**Comment by jjglaser** [comment] 2022-06-07 15:26
I'm following your work @AlexPresso and appreciate it very much so keep on doing so. I've also tested the "new_wrapper" in accordance to the Chromecast issue and can confim that it's working like a charm. So kind regards...

**Closed** 2022-06-14 05:05 UTC
