### ISSUE TITLE
not working with the samsung tv app 

### ISSUE THREAD

**Issue by wonderingStars** [AlexPresso/VideoStation-FFMPEG-Patcher#72] opened 2023-06-25 07:55 UTC
this isn't working with the Samsung tv app the video  plays but no sound . it does work with the internet browser on the tv but crashes 

DS1019+

 dsm 7.1.1-42962 

Samsung free style projector app 
and the app ver : 10.07-81
SynoCommunity FFMPEG Version: [] 6
Advanced Media Extensions version: 3.0.1-2004

no error file were created 
using this command  ls -al | grep ffmpeg

the videos all play but they have no sound on the tv app . the only work with the web bowers

**Comment by AlexPresso** [comment] 2023-06-25 09:53
Hello,

Please provide all the specs and details from the issue template.

**Comment by wonderingStars** [comment] 2023-06-25 11:40
Sure it’s version 10.07-81 disk station it’s the Samsung free style projector. Sent from my iPhoneOn 25 Jun 2023, at 10:54, AlexPresso ***@***.***> wrote:﻿
Hello,
Please provide all the specs and details from the issue template.

**Comment by ner00** [comment] 2023-06-25 15:22
@wonderingStars Clearly not following the template. Here you go:

# Before posting any bug issue, please make sure you have patched a clean VideoStation / AME install by doing the following:
- Uninstall VideoStation (keep your library)
- Uninstall Advanced Media Extensions
- Re-install VideoStation (it should also ask to install Advanced Media Extensions)
- Run the patch

**System details**
- Synology model: [Synology NAS model]
- DSM version: [version]
- SynoCommunity FFMPEG Version: [version]
- VideoStation version: [version]
- Advanced Media Extensions version: [version / "none" if you don't have it installed]

**Describe the bug**
A clear and concise description of what the bug is.

**Provide Log files**
- Start the video on VideoStation, wait for the video to play and put the browser in background (keep the video playing)
- Connect through SSH ([help](https://www.synology.com/en-global/knowledgebase/DSM/tutorial/General_Setup/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet))
- Switch to root user: `sudo -i`

## `ffmpeg.log` (containing the ffmpeg-wrapper execution logs)
- Go to the temporary directory: `cd /tmp`
- Type `ls -al | grep ffmpeg` to list all files containing "ffmpeg" and check you have one named `ffmpeg.log`
- Type `tail -200 ffmpeg.log` to print the last 200 lines to the console
- Copy paste those lines in a new [gist](https://gist.github.com/)
- Add the gist link to the issue

## `ffmpeg-xxxx.stderr` (containing chunks transcoding operations)
- When you ran `ls -al | grep ffmpeg` you should have seen another file that looks like `ffmpeg-xxxx.stderr` in case of error, the file may not be there, in that specific case, you can ignore these steps.
- Type `tail -100 ffmpeg-xxxx.stderr` (replacing the filename by the correct one)
- Copy paste those lines in a new [gist](https://gist.github.com/)
- Type `head -300 ffmpeg-xxxx.stderr` (replacing the filename by the correct one)
- Copy paste those lines in another new [gist](https://gist.github.com/)
- Copy paste all the gists links in the issue

**Additional context**
Add any other context about the problem here.

**Comment by wonderingStars** [comment] 2023-06-25 16:12
i have updated it with the information you asked for

**Comment by AlexPresso** [comment] 2023-06-25 20:10
Hello, thank you for updating your message.

I need to check something with DSVideo app on Samsung TV. Because I also have a Samsung TV and I'm using the app but in general all videos are playing with soundcorrectly.

I only had this similar issue one time, and was not able to fix it because web version was working fine. I will check but my guess is that if there's no related log files, is because the DSVideo app on Samsung TV is not using the patch. 

Maybe they're using an embedded version of ffmpeg instead of the NAS ffmpeg version.

**Comment by wonderingStars** [comment] 2023-06-25 21:04
ok so i guess i cant fix this that is a shame

**Comment by wonderingStars** [comment] 2023-06-27 09:08
could you find a way to trans code all video to the correct format while streaming so the un patched software would still play them

**Comment by AlexPresso** [comment] 2023-06-27 09:37
This is not the purpose of the wrapper.

If the wrapper is not used by Samsung TV app, you will have to transcode the videos by yourself, maybe using the "offline transcoding" option in VideoStation or by using another tool on your NAS or computer.

**Comment by AlexPresso** [comment] 2023-07-23 10:08
Hey there,

I can confirm the Samsung TV/mobile app (DS Video) is not using the wrapper at all, this bug is related with the DS Video app itself and I can't do anything about it with the wrapper.

Sorry, as this issue is not related to the wrapper I'll close it. But as I could reproduce the issue with a recent movie, I'll continue to look for a solution on my own and re-open this issue if I have anything working.

**Closed by AlexPresso** 2023-07-23 10:08 UTC
